apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: cohesion
    meta.helm.sh/release-namespace: phziot
  creationTimestamp: "2023-02-06T11:55:12Z"
  generation: 3
  labels:
    app: cohesion-frontend
    app.kubernetes.io/managed-by: Helm
  name: cohesion-frontend
  namespace: phziot
  resourceVersion: "12580335"
  selfLink: /apis/apps/v1/namespaces/phziot/deployments/cohesion-frontend
  uid: d90a1e9a-b018-4d69-8bb3-90583b174a38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cohesion-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cohesion-frontend
    spec:
      containers:
      - image: local-docker-registry:5001/merck-frontend:v1.5.7
        imagePullPolicy: IfNotPresent
        livenessProbe:
 failureThreshold: 3
          httpGet:
            path: /merck/statics/wso2config.js
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: frontend
        ports:
        - containerPort: 443
          name: port443
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /merck/statics/wso2config.js
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "4"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 2Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /opt/cisco/merck/certs
          name: nginx-cm-certs
        - mountPath: /etc/nginx/sites-available
          name: merck-nginx-config
 - mountPath: /opt/cisco/merck/statics/config
          name: merck-ui-parameters
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: cx-connected-pharma-merck-pull-secret
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: nginx-cm-certs
        name: nginx-cm-certs
      - configMap:
          defaultMode: 420
          name: merck-nginx-config
        name: merck-nginx-config
      - configMap:
          defaultMode: 420
          name: nginx-cm-parameters
        name: merck-ui-parameters
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-02-06T11:55:12Z"
    lastUpdateTime: "2023-02-06T11:55:48Z"
    message: ReplicaSet "cohesion-frontend-6d8549447c" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-04-09T15:23:59Z"
    lastUpdateTime: "2023-04-09T15:23:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 3
  readyReplicas: 1
 replicas: 1
  updatedReplicas: 1


